shallow_clone: true

# version format
version: 1.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

cache:
  - 'C:\projects\internetsimulator\Tulpep.InternetSimulator\packages'

# Do not build on tags (GitHub only)
skip_tags: true

configuration: Release

# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


environment:
  sign_tool: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe'
  artifact_path: 'C:\projects\internetsimulator\Tulpep.InternetSimulator\Tulpep.InternetSimulator\bin\Release\InternetSimulator.exe'
  timestamp_url: 'http://timestamp.verisign.com/scripts/timstamp.dll'
  pfx_file: 'C:\projects\internetsimulator\Tulpep.pfx'
  pfx_password:
    secure: LdcyoQhXm2P2QuFz/ogRYpACnJeZDyka/QBzMKJkKKE=

before_build:
 - nuget restore Tulpep.InternetSimulator\Tulpep.InternetSimulator.sln

after_build:
  - cmd: '"%sign_tool%" sign /f "%pfx_file%" /p %pfx_password% /t %timestamp_url% "%artifact_path%"'

artifacts:
  - path: '**\bin\Release\InternetSimulator.exe'
    name: InternetSimulator.exe

deploy:
  release: InternetSimulator-v$(appveyor_build_version)
  provider: GitHub
  description: ''
  auth_token:
    secure: nGvHoLNrH4j9xxQF0wMmlLRlVkflplJhlPqn9VMcv1llIQi+PQYVKhpuOcMJqHnh
  artifact: InternetSimulator.exe
  draft: false
  prerelease: false
  on:
    branch: master
